title: bobdry.com
email: bobdry@gmail.com
description: Draw me something.
baseurl: /illus/
url: ""

twitter_username: bobbyDdry
github_username:  bobdry

# Build settings
markdown: kramdown

lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Collections
collections:
  campbell:
    output: true
    permalink: :collection/:name
  con:
    output: true
    permalink: :collection/:name
  crown:
    output: true
    permalink: :collection/:name
  five:
    output: true
    permalink: :collection/:name
  hero:
    output: true
    permalink: :collection/:name
  ice:
    output: true
    permalink: :collection/:name
  izaak:
    output: true
    permalink: :collection/:name
  kids:
    output: true
    permalink: :collection/:name
  nature:
    output: true
    permalink: :collection/:name
  guada:
    output: true
    permalink: :collection/:name
plugins:
    - jekyll-feed

# bundle exec jekyll serve