# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: bobdry.com
email: bobdry@gmail.com
description: portfolio website for my nice drawings
baseurl: /
url: ""

# http://127.0.0.1:4000  ""
# http://bobdry.com.s3-website-us-east-1.amazonaws.com /_site

twitter_username: elbobmasgrande
github_username:  bobdry

# Build settings
markdown: kramdown
collections:
  campbell:
    output: true
    permalink: /:collection/:name
  five:
    output: true
    permalink: /:collection/:name
  izaak:
    output: true
    permalink: /:collection/:name
  kids:
    output: true
    permalink: /:collection/:name
  nature:
    output: true
    permalink: /:collection/:name
  guada:
    output: true
    permalink: /:collection/:name
plugins:
    - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
