title: bobdry.com
email: bobdry@gmail.com
description: portfolio website for my nice drawings
baseurl: /illus/
url: ""

twitter_username: elbobmasgrande
github_username:  bobdry

# Build settings
markdown: kramdown
collections:
  campbell:
    output: true
    permalink: /:collection/:name
  hatch:
    output: true
    permalink: /:collection/:name
  izaak:
    output: true
    permalink: /:collection/:name
  kids:
    output: true
    permalink: /:collection/:name
  nature:
    output: true
    permalink: /:collection/:name
  guada:
    output: true
    permalink: /:collection/:name
plugins:
    - jekyll-feed